
#include <type_traits>
#include <cstring>
#include "UpdateFieldNameMap.h"

struct NameMapping
{
    char const* NewName;
    char const* OldName;
};

NameMapping NameMap[] =
{
    { "CGObjectData::m_guid", "OBJECT_FIELD_GUID" },
    { "CGObjectData::m_data", "OBJECT_FIELD_DATA" },
    { "CGObjectData::m_type", "OBJECT_FIELD_TYPE" },
    { "CGObjectData::m_entryID", "OBJECT_FIELD_ENTRY" },
    { "CGObjectData::m_dynamicFlags", "OBJECT_DYNAMIC_FLAGS" },
    { "CGObjectData::m_scale", "OBJECT_FIELD_SCALE_X" },

    { "CGItemData::m_owner", "ITEM_FIELD_OWNER" },
    { "CGItemData::m_containedIn", "ITEM_FIELD_CONTAINED" },
    { "CGItemData::m_creator", "ITEM_FIELD_CREATOR" },
    { "CGItemData::m_giftCreator", "ITEM_FIELD_GIFTCREATOR" },
    { "CGItemData::m_stackCount", "ITEM_FIELD_STACK_COUNT" },
    { "CGItemData::m_expiration", "ITEM_FIELD_DURATION" },
    { "CGItemData::m_spellCharges", "ITEM_FIELD_SPELL_CHARGES" },
    { "CGItemData::m_dynamicFlags", "ITEM_FIELD_FLAGS" },
    { "CGItemData::m_enchantment", "ITEM_FIELD_ENCHANTMENT" },
    { "CGItemData::m_propertySeed", "ITEM_FIELD_PROPERTY_SEED" },
    { "CGItemData::m_randomPropertiesID", "ITEM_FIELD_RANDOM_PROPERTIES_ID" },
    { "CGItemData::m_durability", "ITEM_FIELD_DURABILITY" },
    { "CGItemData::m_maxDurability", "ITEM_FIELD_MAXDURABILITY" },
    { "CGItemData::m_createPlayedTime", "ITEM_FIELD_CREATE_PLAYED_TIME" },
    { "CGItemData::m_modifiersMask", "ITEM_FIELD_MODIFIERS_MASK" },
    { "CGItemData::m_contextID", "ITEM_FIELD_CONTEXT_ID" },
    { "CGItemData::m_context", "ITEM_FIELD_CONTEXT" },
    { "CGItemData::m_artifactXP", "ITEM_FIELD_ARTIFACT_XP" },
    { "CGItemData::m_itemAppearanceModID", "ITEM_FIELD_APPEARANCE_MOD_ID" },

    { "CGItemDynamicData::m_modifiers", "ITEM_DYNAMIC_FIELD_MODIFIERS" },
    { "CGItemDynamicData::m_bonusListIDs", "ITEM_DYNAMIC_FIELD_BONUSLIST_IDS" },
    { "CGItemDynamicData::m_artifactPowers", "ITEM_DYNAMIC_FIELD_ARTIFACT_POWERS" },
    { "CGItemDynamicData::m_gems", "ITEM_DYNAMIC_FIELD_GEMS" },
    { "CGItemDynamicData::m_relicTalentData", "ITEM_DYNAMIC_FIELD_RELIC_TALENT_DATA" },

    { "CGContainerData::m_slots", "CONTAINER_FIELD_SLOT_1" },
    { "CGContainerData::m_numSlots", "CONTAINER_FIELD_NUM_SLOTS" },

    { "CGAzeriteEmpoweredItemData::m_selections", "AZERITE_EMPOWERED_ITEM_FIELD_SELECTIONS" },

    { "CGAzeriteItemData::m_xp", "AZERITE_ITEM_FIELD_XP" },
    { "CGAzeriteItemData::m_level", "AZERITE_ITEM_FIELD_LEVEL" },
    { "CGAzeriteItemData::m_auraLevel", "AZERITE_ITEM_FIELD_AURA_LEVEL" },
    { "CGAzeriteItemData::m_knowledgeLevel", "AZERITE_ITEM_FIELD_KNOWLEDGE_LEVEL" },
    { "CGAzeriteItemData::m_DEBUGknowledgeWeek", "AZERITE_ITEM_FIELD_DEBUG_KNOWLEDGE_WEEK" },

    { "CGUnitData::charm", "UNIT_FIELD_CHARM" },
    { "CGUnitData::summon", "UNIT_FIELD_SUMMON" },
    { "CGUnitData::critter", "UNIT_FIELD_CRITTER" },
    { "CGUnitData::charmedBy", "UNIT_FIELD_CHARMEDBY" },
    { "CGUnitData::summonedBy", "UNIT_FIELD_SUMMONEDBY" },
    { "CGUnitData::createdBy", "UNIT_FIELD_CREATEDBY" },
    { "CGUnitData::demonCreator", "UNIT_FIELD_DEMON_CREATOR" },
    { "CGUnitData::target", "UNIT_FIELD_TARGET" },
    { "CGUnitData::battlePetCompanionGUID", "UNIT_FIELD_BATTLE_PET_COMPANION_GUID" },
    { "CGUnitData::battlePetDBID", "UNIT_FIELD_BATTLE_PET_DB_ID" },
    { "CGUnitData::channelObject", "UNIT_FIELD_CHANNEL_OBJECT" },
    { "CGUnitData::channelSpell", "UNIT_CHANNEL_SPELL" },
    { "CGUnitData::channelSpellXSpellVisual", "UNIT_CHANNEL_SPELL_X_SPELL_VISUAL" },
    { "CGUnitData::channelData", "UNIT_FIELD_CHANNEL_DATA" },
    { "CGUnitData::summonedByHomeRealm", "UNIT_FIELD_SUMMONED_BY_HOME_REALM" },
    { "CGUnitData::sex", "UNIT_FIELD_BYTES_0" },
    { "CGUnitData::displayPower", "UNIT_FIELD_DISPLAY_POWER" },
    { "CGUnitData::overrideDisplayPowerID", "UNIT_FIELD_OVERRIDE_DISPLAY_POWER_ID" },
    { "CGUnitData::health", "UNIT_FIELD_HEALTH" },
    { "CGUnitData::power", "UNIT_FIELD_POWER" },
    { "CGUnitData::maxHealth", "UNIT_FIELD_MAXHEALTH" },
    { "CGUnitData::maxPower", "UNIT_FIELD_MAXPOWER" },
    { "CGUnitData::powerRegenFlatModifier", "UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER" },
    { "CGUnitData::powerRegenInterruptedFlatModifier", "UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER" },
    { "CGUnitData::level", "UNIT_FIELD_LEVEL" },
    { "CGUnitData::effectiveLevel", "UNIT_FIELD_EFFECTIVE_LEVEL" },
    { "CGUnitData::factionTemplate", "UNIT_FIELD_FACTIONTEMPLATE" },
    { "CGUnitData::virtualItemID", "UNIT_VIRTUAL_ITEM_SLOT_ID" },
    { "CGUnitData::virtualItems", "UNIT_VIRTUAL_ITEM_SLOT_ID" },
    { "CGUnitData::flags", "UNIT_FIELD_FLAGS" },
    { "CGUnitData::flags2", "UNIT_FIELD_FLAGS_2" },
    { "CGUnitData::flags3", "UNIT_FIELD_FLAGS_3" },
    { "CGUnitData::auraState", "UNIT_FIELD_AURASTATE" },
    { "CGUnitData::attackRoundBaseTime", "UNIT_FIELD_BASEATTACKTIME" },
    { "CGUnitData::rangedAttackRoundBaseTime", "UNIT_FIELD_RANGEDATTACKTIME" },
    { "CGUnitData::boundingRadius", "UNIT_FIELD_BOUNDINGRADIUS" },
    { "CGUnitData::combatReach", "UNIT_FIELD_COMBATREACH" },
    { "CGUnitData::displayID", "UNIT_FIELD_DISPLAYID" },
    { "CGUnitData::nativeDisplayID", "UNIT_FIELD_NATIVEDISPLAYID" },
    { "CGUnitData::mountDisplayID", "UNIT_FIELD_MOUNTDISPLAYID" },
    { "CGUnitData::minDamage", "UNIT_FIELD_MINDAMAGE" },
    { "CGUnitData::maxDamage", "UNIT_FIELD_MAXDAMAGE" },
    { "CGUnitData::minOffHandDamage", "UNIT_FIELD_MINOFFHANDDAMAGE" },
    { "CGUnitData::maxOffHandDamage", "UNIT_FIELD_MAXOFFHANDDAMAGE" },
    { "CGUnitData::animTier", "UNIT_FIELD_BYTES_1" },
    { "CGUnitData::petNumber", "UNIT_FIELD_PETNUMBER" },
    { "CGUnitData::petNameTimestamp", "UNIT_FIELD_PET_NAME_TIMESTAMP" },
    { "CGUnitData::petExperience", "UNIT_FIELD_PETEXPERIENCE" },
    { "CGUnitData::petNextLevelExperience", "UNIT_FIELD_PETNEXTLEVELEXP" },
    { "CGUnitData::modCastingSpeed", "UNIT_MOD_CAST_SPEED" },
    { "CGUnitData::modSpellHaste", "UNIT_MOD_CAST_HASTE" },
    { "CGUnitData::modHaste", "UNIT_FIELD_MOD_HASTE" },
    { "CGUnitData::modRangedHaste", "UNIT_FIELD_MOD_RANGED_HASTE" },
    { "CGUnitData::modHasteRegen", "UNIT_FIELD_MOD_HASTE_REGEN" },
    { "CGUnitData::modTimeRate", "UNIT_FIELD_MOD_TIME_RATE" },
    { "CGUnitData::createdBySpell", "UNIT_CREATED_BY_SPELL" },
    { "CGUnitData::npcFlags", "UNIT_NPC_FLAGS" },
    { "CGUnitData::emoteState", "UNIT_NPC_EMOTESTATE" },
    { "CGUnitData::stats", "UNIT_FIELD_STAT" },
    { "CGUnitData::statPosBuff", "UNIT_FIELD_POSSTAT" },
    { "CGUnitData::statNegBuff", "UNIT_FIELD_NEGSTAT" },
    { "CGUnitData::resistances", "UNIT_FIELD_RESISTANCES" },
    { "CGUnitData::resistanceBuffModsPositive", "UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE" },
    { "CGUnitData::resistanceBuffModsNegative", "UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE" },
    { "CGUnitData::modBonusArmor", "UNIT_FIELD_MOD_BONUS_ARMOR" },
    { "CGUnitData::baseMana", "UNIT_FIELD_BASE_MANA" },
    { "CGUnitData::baseHealth", "UNIT_FIELD_BASE_HEALTH" },
    { "CGUnitData::shapeshiftForm", "UNIT_FIELD_BYTES_2" },
    { "CGUnitData::attackPower", "UNIT_FIELD_ATTACK_POWER" },
    { "CGUnitData::attackPowerModPos", "UNIT_FIELD_ATTACK_POWER_MOD_POS" },
    { "CGUnitData::attackPowerModNeg", "UNIT_FIELD_ATTACK_POWER_MOD_NEG" },
    { "CGUnitData::attackPowerMultiplier", "UNIT_FIELD_ATTACK_POWER_MULTIPLIER" },
    { "CGUnitData::rangedAttackPower", "UNIT_FIELD_RANGED_ATTACK_POWER" },
    { "CGUnitData::rangedAttackPowerModPos", "UNIT_FIELD_RANGED_ATTACK_POWER_MOD_POS" },
    { "CGUnitData::rangedAttackPowerModNeg", "UNIT_FIELD_RANGED_ATTACK_POWER_MOD_NEG" },
    { "CGUnitData::rangedAttackPowerMultiplier", "UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER" },
    { "CGUnitData::setAttackSpeedAura", "UNIT_FIELD_ATTACK_SPEED_AURA" },
    { "CGUnitData::minRangedDamage", "UNIT_FIELD_MINRANGEDDAMAGE" },
    { "CGUnitData::maxRangedDamage", "UNIT_FIELD_MAXRANGEDDAMAGE" },
    { "CGUnitData::powerCostModifier", "UNIT_FIELD_POWER_COST_MODIFIER" },
    { "CGUnitData::powerCostMultiplier", "UNIT_FIELD_POWER_COST_MULTIPLIER" },
    { "CGUnitData::maxHealthModifier", "UNIT_FIELD_MAXHEALTHMODIFIER" },
    { "CGUnitData::hoverHeight", "UNIT_FIELD_HOVERHEIGHT" },
    { "CGUnitData::minItemLevelCutoff", "UNIT_FIELD_MIN_ITEM_LEVEL_CUTOFF" },
    { "CGUnitData::minItemLevel", "UNIT_FIELD_MIN_ITEM_LEVEL" },
    { "CGUnitData::maxItemLevel", "UNIT_FIELD_MAXITEMLEVEL" },
    { "CGUnitData::wildBattlePetLevel", "UNIT_FIELD_WILD_BATTLEPET_LEVEL" },
    { "CGUnitData::battlePetCompanionNameTimestamp", "UNIT_FIELD_BATTLEPET_COMPANION_NAME_TIMESTAMP" },
    { "CGUnitData::interactSpellID", "UNIT_FIELD_INTERACT_SPELLID" },
    { "CGUnitData::stateSpellVisualID", "UNIT_FIELD_STATE_SPELL_VISUAL_ID" },
    { "CGUnitData::stateAnimID", "UNIT_FIELD_STATE_ANIM_ID" },
    { "CGUnitData::stateAnimKitID", "UNIT_FIELD_STATE_ANIM_KIT_ID" },
    { "CGUnitData::stateWorldEffectID", "UNIT_FIELD_STATE_WORLD_EFFECT_ID" },
    { "CGUnitData::scaleDuration", "UNIT_FIELD_SCALE_DURATION" },
    { "CGUnitData::looksLikeMountID", "UNIT_FIELD_LOOKS_LIKE_MOUNT_ID" },
    { "CGUnitData::looksLikeCreatureID", "UNIT_FIELD_LOOKS_LIKE_CREATURE_ID" },
    { "CGUnitData::lookAtControllerID", "UNIT_FIELD_LOOK_AT_CONTROLLER_ID" },
    { "CGUnitData::lookAtControllerTarget", "UNIT_FIELD_LOOK_AT_CONTROLLER_TARGET" },
    { "CGUnitData::scalingLevelMin", "UNIT_FIELD_SCALING_LEVEL_MIN" },
    { "CGUnitData::scalingLevelMax", "UNIT_FIELD_SCALING_LEVEL_MAX" },
    { "CGUnitData::scalingLevelDelta", "UNIT_FIELD_SCALING_LEVEL_DELTA" },
    { "CGUnitData::sandboxScalingID", "UNIT_FIELD_SANDBOX_SCALING_ID" },
    { "CGUnitData::contentTuningID", "UNIT_FIELD_CONTENT_TUNING_ID" },
    { "CGUnitData::scalingFactionGroup", "UNIT_FIELD_SCALING_FACTION_GROUP" },
    { "CGUnitData::scalingHealthItemLevelCurveID", "UNIT_FIELD_SCALING_HEALTH_ITEM_LEVEL_CURVE_ID" },
    { "CGUnitData::scalingDamageItemLevelCurveID", "UNIT_FIELD_SCALING_DAMAGE_ITEM_LEVEL_CURVE_ID" },
    { "CGUnitData::displayScale", "UNIT_FIELD_DISPLAY_SCALE" },
    { "CGUnitData::nativeXDisplayScale", "UNIT_FIELD_NATIVE_X_DISPLAY_SCALE" },
    { "CGUnitData::bonusResistanceMods", "UNIT_FIELD_BONUS_RESISTANCE_MODS" },
    { "CGUnitData::mainHandWeaponAttackPower", "UNIT_FIELD_MAIN_HAND_WEAPON_ATTACK_POWER" },
    { "CGUnitData::offHandWeaponAttackPower", "UNIT_FIELD_OFF_HAND_WEAPON_ATTACK_POWER" },
    { "CGUnitData::rangedWeaponAttackPower", "UNIT_FIELD_RANGED_HAND_WEAPON_ATTACK_POWER" },
    { "CGUnitData::lifesteal", "UNIT_FIELD_LIFESTEAL" },
    { "CGUnitData::guildGUID", "UNIT_FIELD_GUILD_GUID" },

    { "CGUnitDynamicData::passiveSpells", "UNIT_DYNAMIC_FIELD_PASSIVE_SPELLS" },
    { "CGUnitDynamicData::worldEffects", "UNIT_DYNAMIC_FIELD_WORLD_EFFECTS" },
    { "CGUnitDynamicData::channelObjects", "UNIT_DYNAMIC_FIELD_CHANNEL_OBJECTS" },

    { "CGPlayerData::duelArbiter", "PLAYER_DUEL_ARBITER" },
    { "CGPlayerData::wowAccount", "PLAYER_WOW_ACCOUNT" },
    { "CGPlayerData::lootTargetGUID", "PLAYER_LOOT_TARGET_GUID" },
    { "CGPlayerData::playerFlags", "PLAYER_FLAGS" },
    { "CGPlayerData::playerFlagsEx", "PLAYER_FLAGS_EX" },
    { "CGPlayerData::guildRankID", "PLAYER_GUILDRANK" },
    { "CGPlayerData::guildDeleteDate", "PLAYER_GUILDDELETE_DATE" },
    { "CGPlayerData::guildLevel", "PLAYER_GUILDLEVEL" },
    { "CGPlayerData::hairColorID", "PLAYER_BYTES" },
    { "CGPlayerData::customDisplayOption", "PLAYER_BYTES_2" },
    { "CGPlayerData::inebriation", "PLAYER_BYTES_3" },
    { "CGPlayerData::arenaFaction", "PLAYER_BYTES_4" },
    { "CGPlayerData::duelTeam", "PLAYER_DUEL_TEAM" },
    { "CGPlayerData::guildTimeStamp", "PLAYER_GUILD_TIMESTAMP" },
    { "CGPlayerData::questLog", "PLAYER_QUEST_LOG" },
    { "CGPlayerData::visibleItems", "PLAYER_VISIBLE_ITEM" },
    { "CGPlayerData::playerTitle", "PLAYER_CHOSEN_TITLE" },
    { "CGPlayerData::fakeInebriation", "PLAYER_FAKE_INEBRIATION" },
    { "CGPlayerData::virtualPlayerRealm", "PLAYER_FIELD_VIRTUAL_PLAYER_REALM" },
    { "CGPlayerData::currentSpecID", "PLAYER_FIELD_CURRENT_SPEC_ID" },
    { "CGPlayerData::taxiMountAnimKitID", "PLAYER_FIELD_TAXI_MOUNT_ANIM_KIT_ID" },
    { "CGPlayerData::avgItemLevelTotal", "PLAYER_FIELD_AVG_ITEM_LEVEL_TOTAL" },
    { "CGPlayerData::avgItemLevelEquipped", "PLAYER_FIELD_AVG_ITEM_LEVEL_EQUIPPED" },
    { "CGPlayerData::avgItemLevel", "PLAYER_FIELD_AVG_ITEM_LEVEL" },
    { "CGPlayerData::currentBattlePetBreedQuality", "PLAYER_FIELD_CURRENT_BATTLE_PET_BREED_QUALITY" },
    { "CGPlayerData::prestige", "PLAYER_FIELD_PRESTIGE" },
    { "CGPlayerData::honorLevel", "PLAYER_FIELD_HONOR_LEVEL" },

    { "CGPlayerDynamicData::arenaCooldowns", "PLAYER_DYNAMIC_FIELD_ARENA_COOLDOWNS" },

    { "CGActivePlayerData::invSlots", "ACTIVE_PLAYER_FIELD_INV_SLOT_HEAD" },
    { "CGActivePlayerData::farsightObject", "ACTIVE_PLAYER_FIELD_FARSIGHT" },
    { "CGActivePlayerData::knownTitles", "ACTIVE_PLAYER_FIELD_KNOWN_TITLES" },
    { "CGActivePlayerData::coinage", "ACTIVE_PLAYER_FIELD_COINAGE" },
    { "CGActivePlayerData::XP", "ACTIVE_PLAYER_FIELD_XP" },
    { "CGActivePlayerData::nextLevelXP", "ACTIVE_PLAYER_FIELD_NEXT_LEVEL_XP" },
    { "CGActivePlayerData::trialXP", "ACTIVE_PLAYER_FIELD_TRIAL_XP" },
    { "CGActivePlayerData::skill", "ACTIVE_PLAYER_FIELD_SKILL_LINEID" },
    { "CGActivePlayerData::characterPoints", "ACTIVE_PLAYER_FIELD_CHARACTER_POINTS" },
    { "CGActivePlayerData::maxTalentTiers", "ACTIVE_PLAYER_FIELD_MAX_TALENT_TIERS" },
    { "CGActivePlayerData::trackCreatureMask", "ACTIVE_PLAYER_FIELD_TRACK_CREATURES" },
    { "CGActivePlayerData::trackResourceMask", "ACTIVE_PLAYER_FIELD_TRACK_RESOURCES" },
    { "CGActivePlayerData::mainhandExpertise", "ACTIVE_PLAYER_FIELD_EXPERTISE" },
    { "CGActivePlayerData::offhandExpertise", "ACTIVE_PLAYER_FIELD_OFFHAND_EXPERTISE" },
    { "CGActivePlayerData::rangedExpertise", "ACTIVE_PLAYER_FIELD_RANGED_EXPERTISE" },
    { "CGActivePlayerData::combatRatingExpertise", "ACTIVE_PLAYER_FIELD_COMBAT_RATING_EXPERTISE" },
    { "CGActivePlayerData::blockPercentage", "ACTIVE_PLAYER_FIELD_BLOCK_PERCENTAGE" },
    { "CGActivePlayerData::dodgePercentage", "ACTIVE_PLAYER_FIELD_DODGE_PERCENTAGE" },
    { "CGActivePlayerData::dodgePercentageFromAttribute", "ACTIVE_PLAYER_FIELD_DODGE_PERCENTAGE_FROM_ATTRIBUTE" },
    { "CGActivePlayerData::parryPercentage", "ACTIVE_PLAYER_FIELD_PARRY_PERCENTAGE" },
    { "CGActivePlayerData::parryPercentageFromAttribute", "ACTIVE_PLAYER_FIELD_PARRY_PERCENTAGE_FROM_ATTRIBUTE" },
    { "CGActivePlayerData::critPercentage", "ACTIVE_PLAYER_FIELD_CRIT_PERCENTAGE" },
    { "CGActivePlayerData::rangedCritPercentage", "ACTIVE_PLAYER_FIELD_RANGED_CRIT_PERCENTAGE" },
    { "CGActivePlayerData::offhandCritPercentage", "ACTIVE_PLAYER_FIELD_OFFHAND_CRIT_PERCENTAGE" },
    { "CGActivePlayerData::spellCritPercentage", "ACTIVE_PLAYER_FIELD_SPELL_CRIT_PERCENTAGE1" },
    { "CGActivePlayerData::shieldBlock", "ACTIVE_PLAYER_FIELD_SHIELD_BLOCK" },
    { "CGActivePlayerData::shieldBlockCritPercentage", "ACTIVE_PLAYER_FIELD_SHIELD_BLOCK_CRIT_PERCENTAGE" },
    { "CGActivePlayerData::mastery", "ACTIVE_PLAYER_FIELD_MASTERY" },
    { "CGActivePlayerData::amplify", "ACTIVE_PLAYER_FIELD_AMPLIFY" },
    { "CGActivePlayerData::multistrike", "ACTIVE_PLAYER_FIELD_MULTISTRIKE" },
    { "CGActivePlayerData::multistrikeEffect", "ACTIVE_PLAYER_FIELD_MULTISTRIKE_EFFECT" },
    { "CGActivePlayerData::readiness", "ACTIVE_PLAYER_FIELD_READINESS" },
    { "CGActivePlayerData::speed", "ACTIVE_PLAYER_FIELD_SPEED" },
    { "CGActivePlayerData::avoidance", "ACTIVE_PLAYER_FIELD_AVOIDANCE" },
    { "CGActivePlayerData::sturdiness", "ACTIVE_PLAYER_FIELD_STURDINESS" },
    { "CGActivePlayerData::cleave", "ACTIVE_PLAYER_FIELD_CLEAVE" },
    { "CGActivePlayerData::versatility", "ACTIVE_PLAYER_FIELD_VERSATILITY" },
    { "CGActivePlayerData::versatilityBonus", "ACTIVE_PLAYER_FIELD_VERSATILITY_BONUS" },
    { "CGActivePlayerData::pvpPowerDamage", "ACTIVE_PLAYER_FIELD_PVP_POWER_DAMAGE" },
    { "CGActivePlayerData::pvpPowerHealing", "ACTIVE_PLAYER_FIELD_PVP_POWER_HEALING" },
    { "CGActivePlayerData::exploredZones", "ACTIVE_PLAYER_FIELD_EXPLORED_ZONES" },
    { "CGActivePlayerData::restInfo", "ACTIVE_PLAYER_FIELD_REST_INFO" },
    { "CGActivePlayerData::restStateBonusPool", "ACTIVE_PLAYER_FIELD_REST_STATE_EXPERIENCE" },
    { "CGActivePlayerData::modDamageDonePos", "ACTIVE_PLAYER_FIELD_MOD_DAMAGE_DONE_POS" },
    { "CGActivePlayerData::modDamageDoneNeg", "ACTIVE_PLAYER_FIELD_MOD_DAMAGE_DONE_NEG" },
    { "CGActivePlayerData::modDamageDonePercent", "ACTIVE_PLAYER_FIELD_MOD_DAMAGE_DONE_PCT" },
    { "CGActivePlayerData::modHealingDonePos", "ACTIVE_PLAYER_FIELD_MOD_HEALING_DONE_POS" },
    { "CGActivePlayerData::modHealingPercent", "ACTIVE_PLAYER_FIELD_MOD_HEALING_PCT" },
    { "CGActivePlayerData::modHealingDonePercent", "ACTIVE_PLAYER_FIELD_MOD_HEALING_DONE_PCT" },
    { "CGActivePlayerData::modPeriodicHealingDonePercent", "ACTIVE_PLAYER_FIELD_MOD_PERIODIC_HEALING_DONE_PERCENT" },
    { "CGActivePlayerData::weaponDmgMultipliers", "ACTIVE_PLAYER_FIELD_WEAPON_DMG_MULTIPLIERS" },
    { "CGActivePlayerData::weaponAtkSpeedMultipliers", "ACTIVE_PLAYER_FIELD_WEAPON_ATK_SPEED_MULTIPLIERS" },
    { "CGActivePlayerData::modSpellPowerPercent", "ACTIVE_PLAYER_FIELD_MOD_SPELL_POWER_PCT" },
    { "CGActivePlayerData::modResiliencePercent", "ACTIVE_PLAYER_FIELD_MOD_RESILIENCE_PERCENT" },
    { "CGActivePlayerData::overrideSpellPowerByAPPercent", "ACTIVE_PLAYER_FIELD_OVERRIDE_SPELL_POWER_BY_AP_PCT" },
    { "CGActivePlayerData::overrideAPBySpellPowerPercent", "ACTIVE_PLAYER_FIELD_OVERRIDE_AP_BY_SPELL_POWER_PERCENT" },
    { "CGActivePlayerData::modTargetResistance", "ACTIVE_PLAYER_FIELD_MOD_TARGET_RESISTANCE" },
    { "CGActivePlayerData::modTargetPhysicalResistance", "ACTIVE_PLAYER_FIELD_MOD_TARGET_PHYSICAL_RESISTANCE" },
    { "CGActivePlayerData::localFlags", "ACTIVE_PLAYER_FIELD_LOCAL_FLAGS" },
    { "CGActivePlayerData::numRespecs", "ACTIVE_PLAYER_FIELD_BYTES" },
    { "CGActivePlayerData::selfResSpell", "ACTIVE_PLAYER_FIELD_SELF_RES_SPELL" },
    { "CGActivePlayerData::pvpMedals", "ACTIVE_PLAYER_FIELD_PVP_MEDALS" },
    { "CGActivePlayerData::buybackPrice", "ACTIVE_PLAYER_FIELD_BUYBACK_PRICE" },
    { "CGActivePlayerData::buybackTimestamp", "ACTIVE_PLAYER_FIELD_BUYBACK_TIMESTAMP" },
    { "CGActivePlayerData::yesterdayHonorableKills", "ACTIVE_PLAYER_FIELD_KILLS" },
    { "CGActivePlayerData::lifetimeHonorableKills", "ACTIVE_PLAYER_FIELD_LIFETIME_HONORABLE_KILLS" },
    { "CGActivePlayerData::watchedFactionIndex", "ACTIVE_PLAYER_FIELD_WATCHED_FACTION_INDEX" },
    { "CGActivePlayerData::combatRatings", "ACTIVE_PLAYER_FIELD_COMBAT_RATING" },
    { "CGActivePlayerData::pvpInfo", "ACTIVE_PLAYER_FIELD_ARENA_TEAM_INFO" },
    { "CGActivePlayerData::maxLevel", "ACTIVE_PLAYER_FIELD_MAX_LEVEL" },
    { "CGActivePlayerData::scalingPlayerLevelDelta", "ACTIVE_PLAYER_FIELD_SCALING_PLAYER_LEVEL_DELTA" },
    { "CGActivePlayerData::maxCreatureScalingLevel", "ACTIVE_PLAYER_FIELD_MAX_CREATURE_SCALING_LEVEL" },
    { "CGActivePlayerData::runeRegen", "ACTIVE_PLAYER_FIELD_RUNE_REGEN" },
    { "CGActivePlayerData::noReagentCostMask", "ACTIVE_PLAYER_FIELD_NO_REAGENT_COST" },
    { "CGActivePlayerData::glyphSlots", "ACTIVE_PLAYER_FIELD_GLYPH_SLOTS" },
    { "CGActivePlayerData::glyphs", "ACTIVE_PLAYER_FIELD_GLYPHS" },
    { "CGActivePlayerData::glyphSlotsEnabled", "ACTIVE_PLAYER_FIELD_GLYPHS_ENABLED" },
    { "CGActivePlayerData::petSpellPower", "ACTIVE_PLAYER_FIELD_PET_SPELL_POWER" },
    { "CGActivePlayerData::researching", "ACTIVE_PLAYER_FIELD_RESEARCHING" },
    { "CGActivePlayerData::professionSkillLine", "ACTIVE_PLAYER_FIELD_PROFESSION_SKILL_LINE" },
    { "CGActivePlayerData::uiHitModifier", "ACTIVE_PLAYER_FIELD_UI_HIT_MODIFIER" },
    { "CGActivePlayerData::uiSpellHitModifier", "ACTIVE_PLAYER_FIELD_UI_SPELL_HIT_MODIFIER" },
    { "CGActivePlayerData::homeRealmTimeOffset", "ACTIVE_PLAYER_FIELD_HOME_REALM_TIME_OFFSET" },
    { "CGActivePlayerData::modPetHaste", "ACTIVE_PLAYER_FIELD_MOD_PET_HASTE" },
    { "CGActivePlayerData::summonedBattlePetGUID", "ACTIVE_PLAYER_FIELD_SUMMONED_BATTLE_PET_ID" },
    { "CGActivePlayerData::numBackpackSlots", "ACTIVE_PLAYER_FIELD_BYTES2" },
    { "CGActivePlayerData::overrideSpellsID", "ACTIVE_PLAYER_FIELD_BYTES3" },
    { "CGActivePlayerData::lfgBonusFactionID", "ACTIVE_PLAYER_FIELD_LFG_BONUS_FACTION_ID" },
    { "CGActivePlayerData::lootSpecID", "ACTIVE_PLAYER_FIELD_LOOT_SPEC_ID" },
    { "CGActivePlayerData::overrideZonePVPType", "ACTIVE_PLAYER_FIELD_OVERRIDE_ZONE_PVP_TYPE" },
    { "CGActivePlayerData::itemLevelDelta", "ACTIVE_PLAYER_FIELD_ITEM_LEVEL_DELTA" },
    { "CGActivePlayerData::bagSlotFlags", "ACTIVE_PLAYER_FIELD_BAG_SLOT_FLAGS" },
    { "CGActivePlayerData::bankBagSlotFlags", "ACTIVE_PLAYER_FIELD_BANK_BAG_SLOT_FLAGS" },
    { "CGActivePlayerData::bankAutoSortDisabled", "ACTIVE_PLAYER_FIELD_BANK_AUTOSORT_DISABLED" },
    { "CGActivePlayerData::bankBagSlotAutoSortDisabled", "ACTIVE_PLAYER_FIELD_BANK_BAG_AUTOSORT_DISABLED" },
    { "CGActivePlayerData::insertItemsLeftToRight", "ACTIVE_PLAYER_FIELD_INSERT_ITEMS_LEFT_TO_RIGHT" },
    { "CGActivePlayerData::questCompleted", "ACTIVE_PLAYER_FIELD_QUEST_COMPLETED" },
    { "CGActivePlayerData::honor", "ACTIVE_PLAYER_FIELD_HONOR" },
    { "CGActivePlayerData::honorNextLevel", "ACTIVE_PLAYER_FIELD_HONOR_NEXT_LEVEL" },
    { "CGActivePlayerData::pvpTierMaxFromWins", "ACTIVE_PLAYER_FIELD_PVP_TIER_MAX_FROM_WINS" },
    { "CGActivePlayerData::pvpLastWeeksTierMaxFromWins", "ACTIVE_PLAYER_FIELD_PVP_LAST_WEEKS_TIER_MAX_FROM_WINS" },

    { "CGActivePlayerDynamicData::researchSites", "ACTIVE_PLAYER_DYNAMIC_FIELD_RESERACH_SITE" },
    { "CGActivePlayerDynamicData::researchSiteProgress", "ACTIVE_PLAYER_DYNAMIC_FIELD_RESEARCH_SITE_PROGRESS" },
    { "CGActivePlayerDynamicData::dailyQuestsCompleted", "ACTIVE_PLAYER_DYNAMIC_FIELD_DAILY_QUESTS" },
    { "CGActivePlayerDynamicData::availableQuestLineXQuestIDs", "ACTIVE_PLAYER_DYNAMIC_FIELD_AVAILABLE_QUEST_LINE_X_QUEST_ID" },
    { "CGActivePlayerDynamicData::heirlooms", "ACTIVE_PLAYER_DYNAMIC_FIELD_HEIRLOOMS" },
    { "CGActivePlayerDynamicData::heirloomFlags", "ACTIVE_PLAYER_DYNAMIC_FIELD_HEIRLOOM_FLAGS" },
    { "CGActivePlayerDynamicData::toys", "ACTIVE_PLAYER_DYNAMIC_FIELD_TOYS" },
    { "CGActivePlayerDynamicData::transmog", "ACTIVE_PLAYER_DYNAMIC_FIELD_TRANSMOG" },
    { "CGActivePlayerDynamicData::conditionalTransmog", "ACTIVE_PLAYER_DYNAMIC_FIELD_CONDITIONAL_TRANSMOG" },
    { "CGActivePlayerDynamicData::selfResSpells", "ACTIVE_PLAYER_DYNAMIC_FIELD_SELF_RES_SPELLS" },
    { "CGActivePlayerDynamicData::characterRestrictions", "ACTIVE_PLAYER_DYNAMIC_FIELD_CHARACTER_RESTRICTIONS" },
    { "CGActivePlayerDynamicData::spellPctModByLabel", "ACTIVE_PLAYER_DYNAMIC_FIELD_SPELL_PCT_MOD_BY_LABEL" },
    { "CGActivePlayerDynamicData::spellFlatModByLabel", "ACTIVE_PLAYER_DYNAMIC_FIELD_SPELL_FLAT_MOD_BY_LABEL" },
    { "CGActivePlayerDynamicData::research", "ACTIVE_PLAYER_DYNAMIC_FIELD_RESERACH" },

    { "CGGameObjectData::m_createdBy", "GAMEOBJECT_FIELD_CREATED_BY" },
    { "CGGameObjectData::m_displayID", "GAMEOBJECT_DISPLAYID" },
    { "CGGameObjectData::m_flags", "GAMEOBJECT_FLAGS" },
    { "CGGameObjectData::m_parentRotation", "GAMEOBJECT_PARENTROTATION" },
    { "CGGameObjectData::m_factionTemplate", "GAMEOBJECT_FACTION" },
    { "CGGameObjectData::m_level", "GAMEOBJECT_LEVEL" },
    { "CGGameObjectData::m_percentHealth", "GAMEOBJECT_BYTES_1" },
    { "CGGameObjectData::m_spellVisualID", "GAMEOBJECT_SPELL_VISUAL_ID" },
    { "CGGameObjectData::m_stateSpellVisualID", "GAMEOBJECT_STATE_SPELL_VISUAL_ID" },
    { "CGGameObjectData::m_spawnTrackingStateAnimID", "GAMEOBJECT_STATE_ANIM_ID" },
    { "CGGameObjectData::m_spawnTrackingStateAnimKitID", "GAMEOBJECT_STATE_ANIM_KIT_ID" },
    { "CGGameObjectData::m_stateWorldEffectID", "GAMEOBJECT_STATE_WORLD_EFFECT_ID" },
    { "CGGameObjectData::m_guildGUID", "GAMEOBJECT_FIELD_GUILD_GUID" },
    { "CGGameObjectData::m_customParam", "GAMEOBJECT_FIELD_CUSTOM_PARAM" },

    { "CGGameObjectDynamicData::enableDoodadSets", "GAMEOBJECT_DYNAMIC_ENABLE_DOODAD_SETS" },

    { "CGDynamicObjectData::m_caster", "DYNAMICOBJECT_CASTER" },
    { "CGDynamicObjectData::m_type", "DYNAMICOBJECT_TYPE" },
    { "CGDynamicObjectData::m_spellXSpellVisualID", "DYNAMICOBJECT_SPELL_X_SPELL_VISUAL_ID" },
    { "CGDynamicObjectData::m_spellID", "DYNAMICOBJECT_SPELLID" },
    { "CGDynamicObjectData::m_radius", "DYNAMICOBJECT_RADIUS" },
    { "CGDynamicObjectData::m_castTime", "DYNAMICOBJECT_CASTTIME" },

    { "CGCorpseData::m_owner", "CORPSE_FIELD_OWNER" },
    { "CGCorpseData::m_partyGUID", "CORPSE_FIELD_PARTY" },
    { "CGCorpseData::m_displayID", "CORPSE_FIELD_DISPLAY_ID" },
    { "CGCorpseData::m_items", "CORPSE_FIELD_ITEM" },
    { "CGCorpseData::m_skinID", "CORPSE_FIELD_BYTES_1" },
    { "CGCorpseData::m_facialHairStyleID", "CORPSE_FIELD_BYTES_2" },
    { "CGCorpseData::m_flags", "CORPSE_FIELD_FLAGS" },
    { "CGCorpseData::m_dynamicFlags", "CORPSE_FIELD_DYNAMIC_FLAGS" },
    { "CGCorpseData::m_factionTemplate", "CORPSE_FIELD_FACTIONTEMPLATE" },
    { "CGCorpseData::m_customDisplayOption", "CORPSE_FIELD_CUSTOM_DISPLAY_OPTION" },
    { "CGCorpseData::m_guildGUID", "CORPSE_FIELD_GUILD_GUID" },

    { "CGAreaTriggerData::m_overrideScaleCurve", "AREATRIGGER_OVERRIDE_SCALE_CURVE" },
    { "CGAreaTriggerData::m_caster", "AREATRIGGER_CASTER" },
    { "CGAreaTriggerData::m_duration", "AREATRIGGER_DURATION" },
    { "CGAreaTriggerData::m_timeToTargetScale", "AREATRIGGER_TIME_TO_TARGET_SCALE" },
    { "CGAreaTriggerData::m_spellID", "AREATRIGGER_SPELLID" },
    { "CGAreaTriggerData::m_spellVisualID", "AREATRIGGER_SPELLVISUALID" },
    { "CGAreaTriggerData::m_spellForVisuals", "AREATRIGGER_SPELL_FOR_VISUALS" },
    { "CGAreaTriggerData::m_spellXSpellVisualID", "AREATRIGGER_SPELL_X_SPELL_VISUAL_ID" },
    { "CGAreaTriggerData::m_boundsRadius2D", "AREATRIGGER_BOUNDS_RADIUS_2D" },
    { "CGAreaTriggerData::m_explicitScale", "AREATRIGGER_EXPLICIT_SCALE" },
    { "CGAreaTriggerData::m_extraScaleCurve", "AREATRIGGER_EXTRA_SCALE_CURVE" },
    { "CGAreaTriggerData::m_timeToTarget", "AREATRIGGER_TIME_TO_TARGET" },
    { "CGAreaTriggerData::m_timeToTargetExtraScale", "AREATRIGGER_TIME_TO_TARGET_EXTRA_SCALE" },
    { "CGAreaTriggerData::m_decalPropertiesID", "AREATRIGGER_DECAL_PROPERTIES_ID" },
    { "CGAreaTriggerData::m_visualAnim", "AREATRIGGER_VISUAL_ANIMATION" },
    { "CGAreaTriggerData::m_creatingEffectGUID", "AREATRIGGER_CREATING_EFFECT_GUID" },

    { "CGSceneObjectData::m_scriptPackageID", "SCENEOBJECT_FIELD_SCRIPT_PACKAGE_ID" },
    { "CGSceneObjectData::m_rndSeedVal", "SCENEOBJECT_FIELD_RND_SEED_VAL" },
    { "CGSceneObjectData::m_createdBy", "SCENEOBJECT_FIELD_CREATEDBY" },
    { "CGSceneObjectData::m_sceneType", "SCENEOBJECT_FIELD_SCENE_TYPE" },

    { "CGConversationData::dummy", "CONVERSATION_FIELD_DUMMY" },
    { "CGConversationData::m_lastLineDuration", "CONVERSATION_FIELD_LAST_LINE_DURATION" },
    { "CGConversationData::m_lastLineEndTime", "CONVERSATION_LAST_LINE_END_TIME" },

    { "CGConversationDynamicData::m_actors", "CONVERSATION_DYNAMIC_FIELD_ACTORS" },
    { "CGConversationDynamicData::m_lines", "CONVERSATION_DYNAMIC_FIELD_LINES" }
};

char const* GetOldName(char const* newName)
{
    using len = std::extent<decltype(NameMap)>;

    for (int i = 0; i < len::value; ++i)
        if (!strcmp(NameMap[i].NewName, newName))
            return NameMap[i].OldName;

    return newName;
}
